spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  temp:
    dirPath: c:/temp/eitcharge_test/temp
  genFile:
    dirPath: c:/temp/eitcharge_test